# pyproject.toml
[tool.poetry]
name = "ner-project"
version = "0.1.0"
description = "BERT NER MLOps Project on 8x A100"
authors = ["Shibaev Aleksand shibaev.am@phystech.edu"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
torch = "^2.1.0"
transformers = "^4.35.0"
pytorch-lightning = "^2.1.0"
hydra-core = "^1.3.2"
dvc = {extras = ["s3"], version = "^3.0.0"} # или [gdrive] если нужно
mlflow = "^2.8.0"
pandas = "^2.1.0"
seqeval = "^1.2.2"
onnx = "^1.15.0"
onnxruntime-gpu = "^1.16.0" # Для инференса на GPU
tqdm = "^4.66.0"
scikit-learn = "^1.3.0"
wandb = "^0.23.0"
dvc-gdrive = "^3.0.1"
pyopenssl = "^25.3.0"
cryptography = "^46.0.3"
onnxscript = "^0.5.6"
streamlit = "^1.51.0"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"