defaults:
  - model: bert_cased
  - data: gmb
  - _self_

trainer:
  max_epochs: 3
  devices: 1
  accelerator: "gpu"
  strategy: "auto"
  precision: "16-mixed"

  log_every_n_steps: 50
  val_check_interval: 100
  check_val_every_n_epoch: null

logger:
  project: "my_unique_ner_project_v1"
  name: "single_gpu_run_final"

mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "ner-bert-experiment"
  log_model: False

paths:
  data_dir: "data"
  plot_dir: "plots"
  model_save_dir: "models"

seed: 42
